name: Mixed inputs with Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        required: true
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: |
          # Perform some operation
          echo "Hello, ${{ github.event.inputs.name }}!"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read input from Excel file
        run: |
          pip install pandas
          python read_input.py
        env:
          INPUT_FILE: input_data.xlsx

      - name: Process input data
        run: |
          pip install pandas
          python process_input.py
        env:
          INPUT_FILE: input_data.xlsx
          OUTPUT_FILE: output_data.xlsx

      - name: Set output environment variable
        env:
          MY_OUTPUT: ${{ steps.process-input.outputs.output_value }}
        run: echo "MY_OUTPUT=${{ env.MY_OUTPUT }}" >> $GITHUB_ENV



