name: Mixed inputs with Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        required: true
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: |
      
  build:        
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v3
      
      - name: My Step
        run: |
          # Perform some operation
          output_value=42
          echo "::set-env name=MY_OUTPUT::$output_value"
        env:
          MY_OUTPUT: ${{ steps.my-step.outputs.output_value }}


