name: Excel Reader

on:
  push:
    branches:
      - main

jobs:
  read-excel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - name: Run script
        run: python main.py input_data.xlsx $(python get_input.py)

